# base image
FROM node:13.8.0-alpine3.10

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Intall deps
RUN apk --no-cache add --virtual builds-deps build-base python git

# install and cache app dependencies
COPY server/package.json /app/package.json
RUN npm install -g knex@0.20.10
RUN npm install
COPY ./server /app

# start app
CMD ["npm", "start"]
