version: "3.7"

services:
  noteapp-client:
    container_name: noteapp-client
    build:
      context: ../
      dockerfile: docker/client/Dockerfile.prod
    ports:
      - "80:80"
  noteapp-server:
    container_name: noteapp-server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile.prod
    ports:
      - "5001:5000"
  noteapp-db:
    image: postgres:9.6.17
    container_name: noteapp-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: somethingsecret
