version: '3.7'

services:
  noteapp-client-dev:
    container_name: noteapp-client-dev
    build:
      context: ../
      dockerfile: docker/client/Dockerfile.dev
    volumes:
      - '../client:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  noteapp-server-dev:
    container_name: noteapp-server-dev
    build:
      context: ../
      dockerfile: docker/server/Dockerfile.dev
    volumes:
      - '../server:/app'
      - '/app/node_modules'
    ports:
      - '5001:5000'
    environment:
      - NODE_ENV=development

  noteapp-db-dev:
    image: postgres:9.6.17
    container_name: noteapp-db-dev
    restart: always
    ports:
      - '54320:5432'
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  noteapp_network:
    driver: bridge

volumes:
  database:
